[theme]
base = "light"
primaryColor = "#1f79ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#111111"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[ui]
initial_sidebar_state="collapsed"   # 👈 Sidebar siempre colapsada al abrir
