[theme]
base = "light"
primaryColor = "#1f79ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#111111"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
# .streamlit/config.toml
[ui]
initial_sidebar_state = "collapsed"

[theme]
base="light"
primaryColor="#1f77b4"
font="sans serif"

[server]
headless = true
